# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d1aa63430dce320c778daa0104c5bb24500fe8a696fe1366dcab5177e0c64822b2fb5f7a80aa15ab897d44afc2fd59ac55ee02c7560bf52d0888981e0fb83893

test:
  secret_key_base: 03cce35cbb2b9c7fb565ea575382553c9e75438ce3a9faecd913d6710e0fabaa64fb5659e706107ee825282f9d4897bf64fde3d05429aef2a660227c069b8003

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
